import { CharacterDef, CharacterId, UserProgress } from '../types';

export const CHARACTERS: Record<CharacterId, CharacterDef> = {
  spark: {
    id: 'spark',
    characterClass: 'shooter',
    classTitle: 'יוֹרֶה קְלִיעִים (Shooter)',
    name: 'סְפַּארְק',
    englishName: 'Spark',
    weaponName: 'אֶקְדַּחֵי לֵיְזֶר כְּפוּלִים (Dual Blasters)',
    tier: 1,
    tierName: 'דְּמוּת יְרִי מְהִירָה',
    tierBadgeColor: 'bg-emerald-500',
    hp: 150,
    speed: 5.6,
    damage: 24,
    bulletsPerShot: 2,
    bulletSpeed: 12,
    bulletRadius: 7,
    bulletColor: '#38bdf8',
    attackType: 'shooter',
    superName: 'מָגֵן אֶנֶרְגְּיָה וּמְטַח יְרִי מָהִיר 🛡️',
    superDesc: 'מַפְעִיל מָגֵן בִּלְתִּי חָדִיר לְ-3.5 שְׁנִיּוֹת וּמְשַׁגֵּר מְטַח שֶׁל 8 קְלִיעֵי פְּלַזְמָה עָצְמָתִיִּים',
    superChargeHitsNeeded: 4,
    lore: 'יוֹרֶה סַיְבֶּר מָהִיר הַחוֹרֵר אֶת יְרִיבָיו בְּצֶמֶד אֶקְדַּחֵי לֵיְזֶר עָצְמָתִיִּים וּמָגֵן פְּלַזְמָה קַטְלָנִי.',
    skins: [
      {
        id: 0,
        name: 'שֵׁרִיף סַיְבֶּר (קְלָאסִי)',
        figureTitle: 'שֵׁרִיף סַיְבֶּר',
        color: '#0284c7',
        glowColor: 'rgba(2, 132, 199, 0.75)',
        accentColor: '#38bdf8',
        hairColor: '#38bdf8',
        armorColor: '#0369a1',
        weaponColor: '#0ea5e9',
        tagline: 'חֲלִיפַת סַיְבֶּר טֶקְטִית עִם צֶמֶד אֶקְדַּחֵי לֵיְזֶר מְהִירִים וּמָגֵן פְּלַזְמָה',
        isUnlockedDefault: true,
      },
      {
        id: 1,
        name: 'קוֹמַנְדּוֹ לֶהָבָה 🔥',
        figureTitle: 'קוֹמַנְדּוֹ לֶהָבָה',
        color: '#ea580c',
        glowColor: 'rgba(234, 88, 12, 0.8)',
        accentColor: '#f97316',
        hairColor: '#fb923c',
        armorColor: '#9a3412',
        weaponColor: '#f97316',
        tagline: 'שִׁרְיוֹן קְרָב כָּתֹם חָסִין חֹם חָמוּשׁ בְּמַפְצִיצֵי פְּלַזְמָה לוֹהֲטִים',
        isUnlockedDefault: true,
      },
      {
        id: 2,
        name: 'צַלָּף זָהָב מַלְכוּתִי 👑',
        figureTitle: 'צַלָּף זָהָב',
        color: '#eab308',
        glowColor: 'rgba(234, 179, 8, 0.85)',
        accentColor: '#facc15',
        hairColor: '#fef08a',
        armorColor: '#854d0e',
        weaponColor: '#fef08a',
        tagline: 'מַדֵּי מִסְדָּר יֻקְרָתִיִּים עִם צֶמֶד אֶקְדַּחֵי זָהָב מְלֻטָּשִׁים בְּדַרְגַּת מַאסְטֶר',
        isUnlockedDefault: true,
      },
    ],
    powerUps: [
      {
        id: 'spark_rapid',
        name: 'כַּדּוּרֵי פְּלַזְמָה מְהִירִים',
        englishName: 'Rapid Plasma',
        icon: '⚡',
        desc: 'מַגְבִּיר אֶת קֶצֶב הַיְּרִי בְּ-25% לִפְגִיעוֹת רְצוּפוֹת',
        statBonus: '+25% מְהִירוּת יְרִי',
        cost: 150,
      },
      {
        id: 'spark_shield',
        name: 'מָגֵן חַשְׁמַלִּי נִטְעָן',
        englishName: 'Recharge Shield',
        icon: '🛡️',
        desc: 'מוֹסִיף 25 נְקֻדּוֹת חַיִּים וּמַקְטִין נֶזֶק מֵאוֹיְבִים',
        statBonus: '+25 חַיִּים מְרַבִּיִּים',
        cost: 200,
      },
      {
        id: 'spark_split',
        name: 'מְטַח פִּזּוּר רָחָב',
        englishName: 'Spread Blast',
        icon: '💥',
        desc: 'מַרְחִיב אֶת קְלִיעֵי הַלֵּיְזֶר כָּךְ שֶׁקַּל יוֹתֵר לִפְגֹּעַ',
        statBonus: '+30% רַדְיוּס קְלִיעִים',
        cost: 250,
      },
    ],
  },

  storm: {
    id: 'storm',
    characterClass: 'swordsman',
    classTitle: 'סַיָּף חֲרָבוֹת (Swordsman)',
    name: 'סוּפָה',
    englishName: 'Storm',
    weaponName: 'קָטָאנַת אֶנֶרְגְּיָה זוֹהֶרֶת (Energy Katana)',
    tier: 2,
    tierName: 'דְּמוּת חֶרֶב מִתְקַדֶּמֶת',
    tierBadgeColor: 'bg-blue-600',
    hp: 160,
    speed: 6.0,
    damage: 32,
    bulletsPerShot: 1,
    bulletSpeed: 11,
    bulletRadius: 12,
    bulletColor: '#60a5fa',
    attackType: 'sword',
    superName: 'סוּפֶּר דָּאשׁ הוּרִיקָן וְחֶרֶב סוּפָה 🌪️',
    superDesc: 'זִנּוּק סְעָרָה מָהִיר קָדִימָה שֶׁמְּבַצֵּעַ שִׁיסוּף קַטְלָנִי וְגוֹרֵם 50 נֶזֶק',
    superChargeHitsNeeded: 4,
    lore: 'סַיֶּפֶת מַאסְטֶר מְיֻמֶּנֶת שֶׁתּוֹקֶפֶת בַּהֲנָפוֹת חֶרֶב זוֹהֲרוֹת וְשִׁיסוּפִים קַטְלָנִיִּים.',
    skins: [
      {
        id: 0,
        name: 'סָמוּרַאי צְלָלִים (קְלָאסִי)',
        figureTitle: 'סָמוּרַאי צְלָלִים',
        color: '#3b82f6',
        glowColor: 'rgba(59, 130, 246, 0.75)',
        accentColor: '#60a5fa',
        hairColor: '#1e293b',
        armorColor: '#1d4ed8',
        weaponColor: '#93c5fd',
        tagline: 'שִׁרְיוֹן סָמוּרַאי קַל עִם קָטָאנַת פְּלָדָה וּקְצֵה אֶנֶרְגְּיָה זוֹהֵר',
        isUnlockedDefault: true,
      },
      {
        id: 1,
        name: 'אֲבִיר הַבָּרָק הַמַּלְכוּתִי ⚡',
        figureTitle: 'אֲבִיר הַבָּרָק',
        color: '#9333ea',
        glowColor: 'rgba(147, 51, 234, 0.8)',
        accentColor: '#c084fc',
        hairColor: '#e9d5ff',
        armorColor: '#6b21a8',
        weaponColor: '#d8b4fe',
        tagline: 'קַסְדַּת כְּנָפַיִם וְשִׁרְיוֹן אֲבִירִים עִם חֶרֶב מְחֻשְׁמֶלֶת בְּעָצְמַת סְעָרָה',
        isUnlockedDefault: true,
      },
      {
        id: 2,
        name: 'נִינְגַּ\'ת אֵשׁ קְרִימְזוֹן 🗡️',
        figureTitle: 'נִינְגַּ\'ת אֵשׁ',
        color: '#e11d48',
        glowColor: 'rgba(225, 29, 72, 0.85)',
        accentColor: '#f43f5e',
        hairColor: '#18181b',
        armorColor: '#9f1239',
        weaponColor: '#fda4af',
        tagline: 'גְּלִימַת נִינְגַּ\'ה חֲמַקְמַקָּה וְחֶרֶב לֶהָבוֹת שֶׁמַּשְׁאִירָה שׁוֹבְלֵי אֵשׁ חוֹתְכִים',
        isUnlockedDefault: true,
      },
    ],
    powerUps: [
      {
        id: 'storm_blade',
        name: 'לַהַב קוֹרֵעַ זוֹהֵר',
        englishName: 'Razor Edge',
        icon: '⚔️',
        desc: 'מַגְדִּיל אֶת נֶזֶק הַשִּׁיסוּף שֶׁל הַחֶרֶב בְּ-10 נְקֻדּוֹת',
        statBonus: '+10 נֶזֶק חֶרֶב',
        cost: 180,
      },
      {
        id: 'storm_speed',
        name: 'צַעַד סַעֲרָה זָרִיז',
        englishName: 'Wind Dash',
        icon: '💨',
        desc: 'מַעֲלֶה אֶת מְהִירוּת הַתְּנוּעָה בַּזִּירָה בְּ-20%',
        statBonus: '+20% מְהִירוּת רִיצָה',
        cost: 220,
      },
      {
        id: 'storm_crit',
        name: 'גַּל שִׁיסוּף מַחַץ',
        englishName: 'Sonic Slash',
        icon: '🌪️',
        desc: 'מְשַׁגֵּר גַּל חֶרֶב עֲנָקִי שֶׁפּוֹגֵעַ בְּאוֹיְבִים מֵרָחוֹק',
        statBonus: '+40% טְוַח חֶרֶב',
        cost: 260,
      },
    ],
  },

  titan: {
    id: 'titan',
    characterClass: 'mage',
    classTitle: 'קוֹסֵם אַרְקֵיין (Archmage)',
    name: 'טִיטָאן',
    englishName: 'Titan',
    weaponName: 'מַטֵּה קְסָמִים וּקְרִיסְטַל קוֹסְמִי (Arcane Staff)',
    tier: 3,
    tierName: 'דְּמוּת קֶסֶם אַגָּדִית',
    tierBadgeColor: 'bg-amber-500',
    hp: 175,
    speed: 4.8,
    damage: 36,
    bulletsPerShot: 1,
    bulletSpeed: 9.5,
    bulletRadius: 14,
    bulletColor: '#a855f7',
    attackType: 'magic',
    superName: 'מְטַר מֵטֵאוֹרִים וּמַכַּת בָּרָק מְשַׁתֶּקֶת ⚡',
    superDesc: 'מַכַּת מַחַץ מָאגִית הַמְּזַמֶּנֶת כַּדּוּרֵי אֶנֶרְגְּיָה הַמְּפוֹצְצִים אֶת הַזִּירָה וּמְשַׁתְּקִים אֶת הָאוֹיֵב לְ-2 שְׁנִיּוֹת',
    superChargeHitsNeeded: 3,
    lore: 'אַרְכִי-קוֹסֵם עַתִּיק שֶׁמְּתַעֵל אֶנֶרְגְּיוֹת מָאגִיּוֹת דֶּרֶךְ מַטֶּה עָצְמָתִי לְהַשְׁמָדַת יְרִיבָיו.',
    skins: [
      {
        id: 0,
        name: 'מְכַשֵּׁף בְּרָקִים קוֹסְמִי (קְלָאסִי)',
        figureTitle: 'מְכַשֵּׁף בְּרָקִים',
        color: '#7c3aed',
        glowColor: 'rgba(124, 58, 237, 0.8)',
        accentColor: '#a78bfa',
        hairColor: '#c4b5fd',
        armorColor: '#5b21b6',
        weaponColor: '#facc15',
        tagline: 'גְּלִימַת קְסָמִים מִיסְטִית עִם מַטֶּה עַתִּיק הַמְּשַׁגֵּר כַּדּוּרֵי בָּרָק קוֹסְמִיִּים',
        isUnlockedDefault: true,
      },
      {
        id: 1,
        name: 'קוֹסֵם אֵשׁ אַרְקֵיין 🔮',
        figureTitle: 'קוֹסֵם אֵשׁ אַרְקֵיין',
        color: '#f59e0b',
        glowColor: 'rgba(245, 158, 11, 0.85)',
        accentColor: '#fbbf24',
        hairColor: '#fed7aa',
        armorColor: '#b45309',
        weaponColor: '#ef4444',
        tagline: 'שׁוֹלֵט בְּלֶהָבוֹת קְסוּמוֹת עִם מַטֶּה עֲטוּר אֶבֶן אֹדֶם לוֹהֶטֶת',
        isUnlockedDefault: true,
      },
      {
        id: 2,
        name: 'שַׂר הַמָּאגְיָה הָאֲפֵלָה 🌑',
        figureTitle: 'שַׂר הַמָּאגְיָה הָאֲפֵלָה',
        color: '#18181b',
        glowColor: 'rgba(234, 179, 8, 0.7)',
        accentColor: '#fbbf24',
        hairColor: '#475569',
        armorColor: '#09090b',
        weaponColor: '#a855f7',
        tagline: 'גְּלִימַת וָאקוּם אֲפֵלָה מְעֻטֶּרֶת בְּרוּנוֹת זָהָב וּמַטֶּה עִם קְרִיסְטַל חָלָל עָמֹק',
        isUnlockedDefault: true,
      },
    ],
    powerUps: [
      {
        id: 'titan_blast',
        name: 'הֵד קוֹסְמִי מִתְפּוֹצֵץ',
        englishName: 'Cosmic Echo',
        icon: '🔮',
        desc: 'מַגְדִּיל אֶת רַדְיוּס פִּצּוּץ כַּדּוּרֵי הַקֶּסֶם בְּ-30%',
        statBonus: '+30% רַדְיוּס פִּצּוּץ',
        cost: 200,
      },
      {
        id: 'titan_health',
        name: 'בִּרְכַּת הָאַרְכִי-קוֹסֵם',
        englishName: 'Archmage Aura',
        icon: '💖',
        desc: 'מַעֲנִיק 40 נְקֻדּוֹת חַיִּים נוֹסָפוֹת לְעַמִידוּת שִׂיא',
        statBonus: '+40 חַיִּים מְרַבִּיִּים',
        cost: 240,
      },
      {
        id: 'titan_stun',
        name: 'שִׁתּוּק סַעֲרַת רַעַם',
        englishName: 'Thunder Stun',
        icon: '⚡',
        desc: 'מַאֲרִיךְ אֶת שִׁתּוּק הַסּוּפֶּר בִּשְׁנִיָּה נוֹסֶפֶת',
        statBonus: '+1 שְׁנִיַּת שִׁתּוּק',
        cost: 280,
      },
    ],
  },

  phoenix: {
    id: 'phoenix',
    characterClass: 'archer',
    classTitle: 'קַשַּׁת אֵשׁ (Fire Archer)',
    name: 'פוֹנִיקְס',
    englishName: 'Phoenix',
    weaponName: 'קֶשֶׁת לֶהָבוֹת עָצְמָתִית (Flame Bow)',
    tier: 2,
    tierName: 'דְּמוּת קַשָּׁת לְהַשָּׂגָה 🏹',
    tierBadgeColor: 'bg-orange-500',
    hp: 155,
    speed: 5.5,
    damage: 30,
    bulletsPerShot: 1,
    bulletSpeed: 12,
    bulletRadius: 8,
    bulletColor: '#f97316',
    attackType: 'arrow',
    superName: 'מְטַר חִצֵּי לֶהָבָה מִתְפּוֹצְצִים 🏹🔥',
    superDesc: 'יוֹרֶה מְטַר חִצֵּי אֵשׁ לוֹהֲטִים הַמִּתְפַּצְּצִים בַּזִּירָה וְגוֹרְמִים 60 נֶזֶק אֵשׁ',
    superChargeHitsNeeded: 4,
    lore: 'קַשָּׁת אֵשׁ מִיתוֹלוֹגִי הַיּוֹרֶה חִצֵּי לֶהָבָה מְדֻיָּקִים וּמַבְעִיר אֶת שְׂדֵה הַקְּרָב.',
    trophyRequirement: 40,
    skins: [
      {
        id: 0,
        name: 'קַשַּׁת לֶהָבָה (קְלָאסִי)',
        figureTitle: 'קַשַּׁת לֶהָבָה',
        color: '#ea580c',
        glowColor: 'rgba(234, 88, 12, 0.85)',
        accentColor: '#fdba74',
        hairColor: '#fed7aa',
        armorColor: '#c2410c',
        weaponColor: '#fbbf24',
        tagline: 'שִׁרְיוֹן נוֹצוֹת אֵשׁ מֻזְהָב עִם קֶשֶׁת לֶהָבוֹת זוֹהֶרֶת',
        isUnlockedDefault: false,
      },
      {
        id: 1,
        name: 'צַלָּף כַּנְפֵי הַשֶּׁמֶשׁ ☀️',
        figureTitle: 'צַלָּף כַּנְפֵי הַשֶּׁמֶשׁ',
        color: '#f59e0b',
        glowColor: 'rgba(245, 158, 11, 0.85)',
        accentColor: '#fef08a',
        hairColor: '#fde047',
        armorColor: '#b45309',
        weaponColor: '#f59e0b',
        tagline: 'כַּנְפֵי זָהָב זוֹהֲרוֹת וְחִצֵּי קֶרֶן שֶׁמֶשׁ קַטְלָנִיִּים',
        isUnlockedDefault: false,
      },
      {
        id: 2,
        name: 'פוֹנִיקְס הַלַּבָּה הַקּוֹסְמִית 🌋',
        figureTitle: 'פוֹנִיקְס הַלַּבָּה',
        color: '#dc2626',
        glowColor: 'rgba(220, 38, 38, 0.9)',
        accentColor: '#f87171',
        hairColor: '#fee2e2',
        armorColor: '#991b1b',
        weaponColor: '#f87171',
        tagline: 'שִׁרְיוֹן בַּזֶּלֶת לוֹהֵט עִם לַבָּה זוֹרֶמֶת וְחִצֵּי מַגְמָה מִתְפּוֹצְצִים',
        isUnlockedDefault: false,
      },
    ],
    powerUps: [
      {
        id: 'phoenix_wings',
        name: 'כַּנְפֵי לֶהָבָה קוֹסְמִיּוֹת',
        englishName: 'Flame Wings',
        icon: '🪶',
        desc: 'מַעֲנִיק 25% מְהִירוּת תְּנוּעָה עִם שׁוֹבַל אֵשׁ מַרְשִׁים',
        statBonus: '+25% מְהִירוּת תְּנוּעָה',
        cost: 200,
      },
      {
        id: 'phoenix_explosive',
        name: 'חֵץ הִתְפּוֹצְצוּת לַבָּה',
        englishName: 'Explosive Arrow',
        icon: '💥',
        desc: 'חִצֵּי הַקֶּשֶׁת מִתְפּוֹצְצִים בִּפְגִיעָה וְגוֹרְמִים 15 נֶזֶק סְבִיבָתִי',
        statBonus: '+15 נֶזֶק פִּצּוּץ אֲזוֹרִי',
        cost: 240,
      },
      {
        id: 'phoenix_rebirth',
        name: 'תְּחִיַּת הַפֿוֹנִיקְס',
        englishName: 'Flame Rebirth',
        icon: '🔥',
        desc: 'מְחַדֵּשׁ מִיָּדִית 40 נְקֻדּוֹת חַיִּים בְּמַצַּב סַכָּנָה',
        statBonus: '+40 רִפּוּי חֵרוּם',
        cost: 300,
      },
    ],
  },

  golem: {
    id: 'golem',
    characterClass: 'heavy',
    classTitle: 'עֲנָק בַּרְזֶל (Heavy Brawler)',
    name: 'גּוֹלֶם',
    englishName: 'Golem',
    weaponName: 'אֶגְרוֹף טִיל וּפַטִּישׁ הִידְרָאוּלִי (Rocket Fist)',
    tier: 3,
    tierName: 'דְּמוּת עֲנָק לְהַשָּׂגָה 🤖',
    tierBadgeColor: 'bg-teal-500',
    hp: 220,
    speed: 4.2,
    damage: 34,
    bulletsPerShot: 1,
    bulletSpeed: 9,
    bulletRadius: 15,
    bulletColor: '#06b6d4',
    attackType: 'rocket_fist',
    superName: 'רְסִיסֵי מַחַץ וּמַכַּת אֲדָמָה 🔨💥',
    superDesc: 'מַנְחִית מַכַּת פַּטִּישׁ עֲנָקִית שֶׁמְּרַסֶּקֶת אֶת הַקַּרְקַע וּפוֹלֶטֶת 6 אֶגְרוֹפֵי טִיל לְכָל כִּוּוּן',
    superChargeHitsNeeded: 3,
    lore: 'עֲנָק בַּרְזֶל טֶכְנוֹלוֹגִי מְשֻׁרְיָן בַּכְּבֵדוּת שֶׁיּוֹרֶה אֶגְרוֹפֵי טִיל וּמוֹחֵץ יְרִיבִים.',
    trophyRequirement: 80,
    skins: [
      {
        id: 0,
        name: 'רוֹבּוֹט טִיטָנְיוּם (קְלָאסִי)',
        figureTitle: 'רוֹבּוֹט טִיטָנְיוּם',
        color: '#0d9488',
        glowColor: 'rgba(13, 148, 136, 0.85)',
        accentColor: '#2dd4bf',
        hairColor: '#5eead4',
        armorColor: '#115e59',
        weaponColor: '#06b6d4',
        tagline: 'שִׁרְיוֹן פְּלָדָה חָסִין וְאֶגְרוֹפֵי פִּסְטוֹן הִידְרָאוּלִיִּים',
        isUnlockedDefault: false,
      },
      {
        id: 1,
        name: 'עֲנָק גַּעֲשִׁי מַגְמָה 🌋',
        figureTitle: 'עֲנָק גַּעֲשִׁי',
        color: '#b91c1c',
        glowColor: 'rgba(185, 28, 28, 0.85)',
        accentColor: '#fca5a5',
        hairColor: '#fecaca',
        armorColor: '#7f1d1d',
        weaponColor: '#ef4444',
        tagline: 'סְלָעִים וְלַבָּה רוֹתַחַת עִם אֶגְרוֹפֵי אֵשׁ הַמְּרַסְּקִים כָּל מִכְשׁוֹל',
        isUnlockedDefault: false,
      },
      {
        id: 2,
        name: 'גּוֹלֶם קְרִיסְטַל קוֹסְמִי 💎',
        figureTitle: 'גּוֹלֶם קְרִיסְטַל',
        color: '#6366f1',
        glowColor: 'rgba(99, 102, 241, 0.9)',
        accentColor: '#a5b4fc',
        hairColor: '#c7d2fe',
        armorColor: '#4338ca',
        weaponColor: '#818cf8',
        tagline: 'גּוֹלֶם גְּבִישֵׁי יָהֲלוֹם קוֹסְמִיִּים הַמַּחֲזִירִים אוֹר זוֹהֵר וּמַחַץ כָּבֵד',
        isUnlockedDefault: false,
      },
    ],
    powerUps: [
      {
        id: 'golem_armor',
        name: 'שִׁרְיוֹן פְּלָדָה מְחֻסָּם',
        englishName: 'Reinforced Steel',
        icon: '🛡️',
        desc: 'מַפְחִית 25% מֵהַנֶּזֶק שֶׁהַגּוֹלֶם סוֹפֵג מֵאוֹיְבִים',
        statBonus: '-25% נֶזֶק נִסְפָּג',
        cost: 220,
      },
      {
        id: 'golem_slam',
        name: 'אֶגְרוֹף מַחַץ הִידְרָאוּלִי',
        englishName: 'Hydraulic Impact',
        icon: '🥊',
        desc: 'מוֹסִיף 15 נֶזֶק לְכָל אֶגְרוֹף טִיל הַנּוֹרֶה מֵהַגּוֹלֶם',
        statBonus: '+15 נֶזֶק אֶגְרוֹף',
        cost: 260,
      },
      {
        id: 'golem_quake',
        name: 'רַעַד אֲדָמָה מַרְחִיק',
        englishName: 'Earthquake Pulse',
        icon: '💥',
        desc: 'פּוֹלֵט גַּל הֶדֶף מַתְמִיד הַמַּרְחִיק אוֹיְבִים הַמִּתְקָרְבִים אֵלָיו',
        statBonus: 'הֲדָפַת אוֹיְבִים סְבִיבָתִית',
        cost: 320,
      },
    ],
  },

  shadow: {
    id: 'shadow',
    characterClass: 'ninja',
    classTitle: 'צַיָּד צְלָלִים (Shadow Ninja)',
    name: 'צֵל',
    englishName: 'Shadow',
    weaponName: 'שׁוּרִיקֶן צְלָלִים זוֹהֵר (Shadow Shuriken)',
    tier: 3,
    tierName: 'דְּמוּת נִינְגַּ\'ה לְהַשָּׂגָה 🥷',
    tierBadgeColor: 'bg-fuchsia-600',
    hp: 145,
    speed: 6.2,
    damage: 18,
    bulletsPerShot: 3,
    bulletSpeed: 13,
    bulletRadius: 7,
    bulletColor: '#c084fc',
    attackType: 'shuriken',
    superName: 'עַרְפִלִּית צְלָלִים וּמַטַּח שׁוּרִיקֶנִים 🌪️🥷',
    superDesc: 'הוֹפֵךְ לְבִלְתִּי נִרְאֶה לְ-3 שְׁנִיּוֹת וּמְשַׁגֵּר מַטַּח שֶׁל 9 כּוֹכְבֵי נִינְגַּ\'ה מְסֻחְרָרִים',
    superChargeHitsNeeded: 4,
    lore: 'צַיָּד צְלָלִים מִסְתּוֹרִי הַנָּע בִּמְהִירוּת הַבָּרָק וְיוֹרֶה כּוֹכְבֵי שׁוּרִיקֶן קַטְלָנִיִּים.',
    trophyRequirement: 120,
    skins: [
      {
        id: 0,
        name: 'נִינְגַּ\'ת צְלָלִים (קְלָאסִי)',
        figureTitle: 'נִינְגַּ\'ת צְלָלִים',
        color: '#701a75',
        glowColor: 'rgba(112, 26, 117, 0.85)',
        accentColor: '#e879f9',
        hairColor: '#f5d0fe',
        armorColor: '#4a044e',
        weaponColor: '#c084fc',
        tagline: 'גְּלִימַת צְלָלִים סְגֻלָּה עִם מַסֵּכַת נִינְגַּ\'ה וְכּוֹכְבֵי שׁוּרִיקֶן חוֹתְכִים',
        isUnlockedDefault: false,
      },
      {
        id: 1,
        name: 'שִׁינוֹבִּי הַבָּרָק הַכָּחֹל ⚡',
        figureTitle: 'שִׁינוֹבִּי הַבָּרָק',
        color: '#0284c7',
        glowColor: 'rgba(2, 132, 199, 0.85)',
        accentColor: '#38bdf8',
        hairColor: '#7dd3fc',
        armorColor: '#0369a1',
        weaponColor: '#38bdf8',
        tagline: 'מַדֵּי שִׁינוֹבִּי כְּחֻלִּים מְהִירִים כְּבָרָק עִם כּוֹכְבֵי לֵיְזֶר מְחֻשְׁמָלִים',
        isUnlockedDefault: false,
      },
      {
        id: 2,
        name: 'רוּחַ צֵל מֻזְהֶבֶת 👑',
        figureTitle: 'רוּחַ צֵל מֻזְהֶבֶת',
        color: '#ca8a04',
        glowColor: 'rgba(202, 138, 4, 0.9)',
        accentColor: '#facc15',
        hairColor: '#fef08a',
        armorColor: '#854d0e',
        weaponColor: '#facc15',
        tagline: 'גְּלִימַת נִינְגַּ\'ה מֻזְהֶבֶת עֲטוּרַת עֲלֵי זָהָב וְכּוֹכְבֵי זָהָב נוֹצְצִים',
        isUnlockedDefault: false,
      },
    ],
    powerUps: [
      {
        id: 'shadow_tri',
        name: 'שׁוּרִיקֶן מְשֻׁלָּשׁ קַטְלָנִי',
        englishName: 'Triple Shuriken',
        icon: '🥷',
        desc: 'יְרִי שְׁלֹשָׁה כּוֹכְבֵי נִינְגַּ\'ה בְּבַת אַחַת בִּפְרִיסָה רְחָבָה',
        statBonus: '+2 כּוֹכְבֵי יְרִי בְּכָל מַטָּח',
        cost: 220,
      },
      {
        id: 'shadow_phantom',
        name: 'צַעַד רְפָאִים מָהִיר',
        englishName: 'Phantom Step',
        icon: '💨',
        desc: 'מַעֲלֶה מְהִירוּת רִיצָה בְּ-25% וּמַאֲפְשֵׁר הִתְחַמְּקוּת חֲלָקָה',
        statBonus: '+25% מְהִירוּת תְּנוּעָה',
        cost: 260,
      },
      {
        id: 'shadow_invis',
        name: 'מָסַךְ עַרְפִלִּית צְלָלִים',
        englishName: 'Smoke Veil',
        icon: '🌫️',
        desc: 'הַסְוָאָה בְּשִׂיחִים גְּדוֹלָה יוֹתֵר וְרִפּוּי אִיטִי בִּזְמַן מַחֲבוֹא',
        statBonus: 'רִפּוּי עַצְמִי בְּשִׂיחִים',
        cost: 320,
      },
    ],
  },
};

export const INITIAL_PROGRESS_KEY = 'brawl_stars_progress_v4';

export const DEFAULT_INITIAL_PROGRESS: UserProgress = {
  coins: 250,
  trophies: 0,
  unlockedCharacters: ['spark', 'storm', 'titan'], // Fully unlocked from the start!
  unlockedSkins: {
    spark: [0, 1, 2], // All 3 skins open!
    storm: [0, 1, 2], // All 3 skins open!
    titan: [0, 1, 2], // All 3 skins open!
    phoenix: [0],
    golem: [0],
    shadow: [0],
  },
  unlockedPowerUps: {
    spark_rapid: true,
    storm_blade: true,
    titan_blast: true,
  },
  equippedPowerUps: {
    spark: 'spark_rapid',
    storm: 'storm_blade',
    titan: 'titan_blast',
    phoenix: 'phoenix_wings',
    golem: 'golem_armor',
    shadow: 'shadow_tri',
  },
  selectedChar: 'spark',
  selectedSkinIdx: 0,
  totalWins: 0,
  totalLosses: 0,
  boxesOpened: 0,
};
